import type { Race, ClassData, SubclassData, Background, FeatData, SpellData, EquipmentData, ClassFeatureData, ClassFeatureEffects } from '@/types/data'

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(path)
  if (!res.ok) throw new Error(`Failed to load ${path}: ${res.status}`)
  return res.json() as Promise<T>
}

// Class-feature description glossary: { _shared: { name: desc }, classSlug: { name: desc } }.
// Class-qualified entry wins over `_shared`; missing names fall back to a UI stub.
export type FeatureDescriptions = Record<string, Record<string, string>>

export interface SetupData {
  races: Record<string, Race>
  classes: Record<string, ClassData>
  subclasses: Record<string, SubclassData>
  backgrounds: Record<string, Background>
  classFeatures: ClassFeatureData
  featureDescriptions: FeatureDescriptions
  // feature name → category key (combat/defense/magic/skill/exploration/support/social/utility).
  // Authored against the descriptions; the Features block prefers it over its keyword heuristic.
  featureCategories: Record<string, string>
  // Always-on class-feature effects, applied at render time (see computeClassFeatureEffects).
  classFeatureEffects: ClassFeatureEffects
}

/** Look up a class-level feature's description: class-qualified first, then `_shared`. */
export function lookupFeatureDescription(
  glossary: FeatureDescriptions | undefined,
  classSlug: string,
  name: string,
): string | undefined {
  if (!glossary) return undefined
  return glossary[classSlug]?.[name] ?? glossary._shared?.[name]
}

let setupCache: Promise<SetupData> | null = null
let featsCache: Promise<Record<string, FeatData>> | null = null
let spellsCache: Promise<Record<string, SpellData>> | null = null
let equipmentCache: Promise<EquipmentData> | null = null

// Cache the result promise, but evict it on rejection so a later call can retry
// instead of replaying a stale failure forever (BUG-26 — e.g. an offline blip
// before the service worker has cached /data, or a 401 from an auth gate).
function memoize<T>(get: () => Promise<T>, set: (p: Promise<T> | null) => void): Promise<T> {
  const p = get().catch(err => { set(null); throw err })
  set(p)
  return p
}

export function loadSetupData(): Promise<SetupData> {
  return setupCache ??= memoize(
    () => Promise.all([
      fetchJson<Record<string, Race>>('/data/races.json'),
      fetchJson<Record<string, ClassData>>('/data/classes.json'),
      fetchJson<Record<string, SubclassData>>('/data/subclasses.json'),
      fetchJson<Record<string, Background>>('/data/backgrounds.json'),
      // class-features.json is generated by build-data; fall back to {} if a stale
      // service-worker cache predates it so setup data still loads.
      fetchJson<ClassFeatureData>('/data/class-features.json').catch(() => ({} as ClassFeatureData)),
      // feature-descriptions.json is optional; fall back to {} if absent/stale cache.
      fetchJson<FeatureDescriptions>('/data/feature-descriptions.json').catch(() => ({} as FeatureDescriptions)),
      // feature-categories.json is optional; fall back to {} so the UI heuristic still works.
      fetchJson<Record<string, string>>('/data/feature-categories.json').catch(() => ({} as Record<string, string>)),
      // class-feature-effects.json is optional; fall back to {} (no always-on feature effects).
      fetchJson<ClassFeatureEffects>('/data/class-feature-effects.json').catch(() => ({} as ClassFeatureEffects)),
    ]).then(([races, classes, subclasses, backgrounds, classFeatures, featureDescriptions, featureCategories, classFeatureEffects]) =>
      ({ races, classes, subclasses, backgrounds, classFeatures, featureDescriptions, featureCategories, classFeatureEffects })),
    p => { setupCache = p },
  )
}

export function loadFeatsData(): Promise<Record<string, FeatData>> {
  return featsCache ??= memoize(
    () => fetchJson<Record<string, FeatData>>('/data/feats.json'),
    p => { featsCache = p },
  )
}

export function loadSpellsData(): Promise<Record<string, SpellData>> {
  return spellsCache ??= memoize(
    () => fetchJson<Record<string, SpellData>>('/data/spells.json'),
    p => { spellsCache = p },
  )
}

export function loadEquipmentData(): Promise<EquipmentData> {
  return equipmentCache ??= memoize(
    () => fetchJson<EquipmentData>('/data/equipment.json'),
    p => { equipmentCache = p },
  )
}
